### ISSUE TITLE
`datas` prop type errors when passing values that aren't strings

### ISSUE THREAD

**Issue by tgrgds** [dolezel/react-csv-downloader#372]
Hiya!

In TypeScript, the `CsvDownload` component compiles and runs as intended when passing in an object such as the following:

```ts
type Thing = {
  id: number;
  name: string;
  birthday: Date;
};

const things: Thing[] = [
  {
    id: 12,
    name: "Bob",
    birthday: new Date(2000, 5, 14),
  },
  {
    id: 69420,
    name: "Tim",
    birthday: new Date(1998, 8, 23),
  },
];
```

However, I get the following type error in my IDE:

```
No overload matches this call.
  Overload 1 of 2, '(props: ICsvDownloadProps | Readonly<ICsvDownloadProps>): CsvDownload', gave the following error.
    Type 'Thing[]' is not assignable to type 'Datas | (() => Datas) | (() => Promise<Datas>) | Promise<Datas>'.
      Type 'Thing[]' is not assignable to type 'Datas'.
        Type 'Thing' is not assignable to type 'string[] | { [key: string]: string | null | undefined; }'.
          Type 'Thing' is not assignable to type '{ [key: string]: string | null | undefined; }'.
            Property 'id' is incompatible with index signature.
              Type 'number' is not assignable to type 'string'.
  Overload 2 of 2, '(props: ICsvDownloadProps, context: any): CsvDownload', gave the following error.
    Type 'Thing[]' is not assignable to type 'Datas | (() => Datas) | (() => Promise<Datas>) | Promise<Datas>'.ts(2769)
```

Because `datas` is expecting `string | null | undefined`, whereas it should allow anything that can be converted to a string (i.e. `string | number | boolean | symbol | object | null | undefined`).

Unless I'm missing something silly, I think it should be changed in this line to suit:
https://github.com/dolezel/react-csv-downloader/blob/319c8a0aaf297946b5add33b729d724a217e27ac/src/lib/csv.ts#L8

**Comment by dolezel** [comment]
I think it should be responsibility of the developer who is using the lib to make sure that data that should be put into csv are properly formatted (which means string, because that is the only type that is not converted).
Though I could extend the type to also accept numbers, I think `Intl.NumberFormat` should be used. Similar with booleans, it would only work in english localization, not sure if people using other languages would be happy to see true/false not converted into their language.
Symbol can't be converted to string.
With Date it is questionable, as the default format is usually not what you want, I would recommend there using Luxon, date-fns or some other lib to do the proper formatting before sending data to csv
![obrazek](https://github.com/user-attachments/assets/0a35a83c-a4a9-4c30-9b78-afdffbd2eee1)
